apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: istio-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 40
    volumeType: gp2
    tags:
      nodegroup-type: worker