---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-easydevop-com
  namespace: istio-ingress
spec:
  secretName: app-easydevop-com-crt
  dnsNames:
    - app.easydevop.com
  issuerRef:
    name: production-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
